### PR TITLE
Animals table

### PR DESCRIPTION
**Pull request by banzaman**
Screenshot (346)
Screenshot (347)](https://user-images.githubusercontent.com/70164878/236434439-b9b2e0a9-77b4-41d8-8106-c2ebb742fdfe.png)
-ec4cdebd-21be-4310-b727-2242393e8c8a.png)
Screenshot (348)
Screenshot (350)
Screenshot (351)
Screenshot (352)
Screenshot (353)
Screenshot (354)

### CODE REVIEW

**Review by Davidosky007 — COMMENTED** [review]
Hi @banzaman 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a descriptive readme kindly customize your readme to suit your project  

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by nahnahdev — CHANGES_REQUESTED** [review]
## Project Status: CHANGES REQUIRED :recycle: 
Hi @banzaman , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Tables created :heavy_check_mark: 
- Data inserted :heavy_check_mark: 
- Professional README :heavy_check_mark: 

## Required Changes ♻️
- [ ] You've done an incredible job so far creating the animal's table, inserting the data, and performing the queries. However, you didn't include screenshots of the results of the queries in the pull request. I noticed you added them in the images folder so I will suggest that you include them in the Pull Request Summary instead :+1: 
- Project Requirement
image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by nahnahdev — APPROVED** [review]
## Project Status: APPROVED :green_circle: 
Hi @banzaman , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights
- All requested changes implemented :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by banzaman** [comment]
Thnak you very much

**Pull request merged**
